----USER DEFINED FUNCTION (SCALAR)
SELECT * FROM [Sales].[SalesTerritory]

CREATE FUNCTION YTDSALES()
RETURNS MONEY
AS
BEGIN
DECLARE @YTDSALES MONEY
SELECT @YTDSALES = SUM(SALESYTD) FROM [Sales].[SalesTerritory]
RETURN @YTDSALES
END


DECLARE @YTDRESULTS AS MONEY
SELECT @YTDRESULTS = dbo.YTDSALES()
PRINT @YTDRESULTS

DROP FUNCTION YTDSALES

----PARAMETER FUNCTION
CREATE FUNCTION YTDGROUP(@GROUP VARCHAR(50))
RETURNS MONEY
AS
BEGIN
DECLARE @YTDSALES AS MONEY
SELECT @YTDSALES = SUM(SALESYTD) FROM [Sales].[SalesTerritory]
WHERE [GROUP] = @GROUP
RETURN @YTDSALES
END

DECLARE @RESULTS AS MONEY
SELECT @RESULTS = dbo.YTDGROUP('Pacific')
PRINT @RESULTS

DROP FUNCTION YTDGROUP

------FUNCTIONS RETURNING TABLES
CREATE FUNCTION ST_TABVALUED(@TERRITORYID INT)
RETURNS TABLE
AS RETURN
SELECT NAME, COUNTRYREGIONCODE, [GROUP], SALESYTD
FROM [Sales].[SalesTerritory]
WHERE TerritoryID = @TERRITORYID

SELECT * FROM dbo.ST_TABVALUED(7)