----RANKING FUNCTIONS

SELECT PostalCode FROM [Person].[Address]
WHERE PostalCode IN ('98052', '98027', '98055', '97205')


SELECT POSTALCODE, ROW_NUMBER() OVER (ORDER BY POSTALCODE) AS 'ROW NUMBER'
, RANK() OVER (ORDER BY POSTALCODE) AS 'RANK'
FROM [Person].[Address]
WHERE POSTALCODE IN ('98052', '98027', '98055', '97205')

--Continuation ranking
SELECT POSTALCODE, ROW_NUMBER() OVER (ORDER BY POSTALCODE) AS 'ROW NUMBER'
, DENSE_RANK() OVER (ORDER BY POSTALCODE) AS 'DENSE RANK'
FROM [Person].[Address]
WHERE POSTALCODE IN ('98052', '98027', '98055', '97205')


--Bucketing - ranked into specific groups (here, it is 10)
SELECT POSTALCODE, ROW_NUMBER() OVER (ORDER BY POSTALCODE) AS 'ROW NUMBER'
, NTILE(10) OVER (ORDER BY POSTALCODE) AS 'NTILE'
FROM [Person].[Address]
WHERE POSTALCODE IN ('98052', '98027', '98055', '97205')
